/**
 * CI Report Formatter
 * ───────────────────
 * Generates Markdown for GitHub PR comments and job summaries.
 * Truncates to stay under GitHub's 65K character limit.
 */

import { SITE_AUDIT } from './config.js';

const MAX_LENGTH = SITE_AUDIT.ci.commentMaxLength;
const MAX_PAGES = SITE_AUDIT.ci.summaryMaxPages;
const MAX_ISSUES = SITE_AUDIT.ci.issueDetailLimit;

/**
 * Generate a full CI report as Markdown.
 *
 * @param {object} opts
 * @param {object} opts.results - The SiteAuditResult from runSiteAudit
 * @param {string} opts.previewUrl - The preview deployment URL
 * @param {string} [opts.commitSha] - The commit SHA
 * @param {string} [opts.runUrl] - Link to the GitHub Actions run
 * @returns {{ summary: string, comment: string }}
 */
export function generateCIReport({ results, previewUrl, commitSha, runUrl }) {
  const { summary } = results;
  const passed = summary.totalFails === 0;

  const lines = [];

  // ── Header ────────────────────────────────────────────────
  lines.push(`## ${passed ? 'All QA Checks Passed' : 'QA Issues Found'}`);
  lines.push('');

  const meta = [];
  if (previewUrl) meta.push(`[Preview](${previewUrl})`);
  if (commitSha) meta.push(`Commit: \`${commitSha.slice(0, 7)}\``);
  if (runUrl) meta.push(`[Workflow Run](${runUrl})`);
  if (meta.length > 0) {
    lines.push(meta.join(' | '));
    lines.push('');
  }

  lines.push(`**${summary.totalPages} pages** audited | **${summary.sampledPages} pages** sampled for heavy audits`);
  lines.push('');

  // ── Summary Table ─────────────────────────────────────────
  lines.push('### Summary');
  lines.push('');
  lines.push('| Audit | Pages Tested | Passed | Failed |');
  lines.push('|-------|-------------|--------|--------|');

  const auditLabels = {
    accessibility: 'Accessibility (axe-core)',
    seo: 'SEO',
    lighthouse: 'Lighthouse',
    pagespeed: 'PageSpeed',
    breakpoints: 'Breakpoints',
    redirects: 'Redirects & Routing',
    links: 'Link Checker',
  };

  for (const [audit, pagesRun] of Object.entries(summary.auditsRun)) {
    const fails = summary.failsByAudit[audit] || 0;
    const passed = pagesRun - fails;
    const icon = fails > 0 ? ' :x:' : ' :white_check_mark:';
    const label = auditLabels[audit] || audit;
    lines.push(`| ${label}${icon} | ${pagesRun} | ${Math.max(0, passed)} | ${fails} |`);
  }

  lines.push('');

  // ── Worst Pages ───────────────────────────────────────────
  if (summary.worstPages && summary.worstPages.length > 0) {
    const pagesWithIssues = summary.worstPages.filter(p => p.fails > 0);
    if (pagesWithIssues.length > 0) {
      lines.push('### Pages with Most Issues');
      lines.push('');
      for (const { url, fails } of pagesWithIssues.slice(0, MAX_PAGES)) {
        const path = safePathname(url);
        lines.push(`- \`${path}\` — ${fails} issue(s)`);
      }
      lines.push('');
    }
  }

  // ── Issue Details (collapsible) ───────────────────────────
  const detailSections = buildDetailSections(results);
  if (detailSections.length > 0) {
    lines.push('### Issue Details');
    lines.push('');
    lines.push(...detailSections);
  }

  // ── Footer ────────────────────────────────────────────────
  lines.push('---');
  lines.push('*Generated by [plasma-qa-tools](https://github.com/nicholasgriffintn/plasma-qa-tools)*');

  const fullComment = lines.join('\n');

  // Truncate if too long
  const comment = truncate(fullComment, MAX_LENGTH);

  // Job summary is a shorter version — just header + table
  const summaryEnd = lines.indexOf('### Pages with Most Issues');
  const summaryLines = summaryEnd > 0 ? lines.slice(0, summaryEnd) : lines;
  const jobSummary = summaryLines.join('\n');

  return { summary: jobSummary, comment };
}

/**
 * Build collapsible detail sections for each audit type with issues.
 */
function buildDetailSections(results) {
  const sections = [];

  // Per-page audit issues (accessibility, SEO)
  for (const [pageUrl, audits] of Object.entries(results.pages)) {
    for (const [auditName, result] of Object.entries(audits)) {
      if (result.failCount === 0) continue;

      const path = safePathname(pageUrl);
      const failedChecks = result.checks.filter(c => !c.passed);

      if (failedChecks.length === 0) continue;

      sections.push(`<details>`);
      sections.push(`<summary><b>${auditName}</b> — <code>${path}</code> (${result.failCount} issue(s))</summary>`);
      sections.push('');

      for (const check of failedChecks.slice(0, MAX_ISSUES)) {
        sections.push(`- :x: ${check.message || check.label}`);
      }
      if (failedChecks.length > MAX_ISSUES) {
        sections.push(`- ... and ${failedChecks.length - MAX_ISSUES} more`);
      }

      // Accessibility: show violation details
      if (auditName === 'accessibility' && result.data?.violations) {
        sections.push('');
        for (const v of result.data.violations.slice(0, MAX_ISSUES)) {
          sections.push(`  - **[${v.impact}]** ${v.help} (${v.nodeCount} elements)`);
        }
        if (result.data.violations.length > MAX_ISSUES) {
          sections.push(`  - ... and ${result.data.violations.length - MAX_ISSUES} more violations`);
        }
      }

      sections.push('');
      sections.push(`</details>`);
      sections.push('');
    }
  }

  // Sampled audit issues (lighthouse, pagespeed, breakpoints)
  for (const [pageUrl, audits] of Object.entries(results.sampled)) {
    for (const [auditName, result] of Object.entries(audits)) {
      if (result.failCount === 0) continue;

      const path = safePathname(pageUrl);
      const failedChecks = result.checks.filter(c => !c.passed);

      if (failedChecks.length === 0) continue;

      sections.push(`<details>`);
      sections.push(`<summary><b>${auditName}</b> — <code>${path}</code> (${result.failCount} issue(s))</summary>`);
      sections.push('');

      for (const check of failedChecks.slice(0, MAX_ISSUES)) {
        const detail = check.threshold != null
          ? `${check.label}: ${check.value}${check.unit || ''} (target: ${check.lowerIsBetter === false ? '>=' : '<='} ${check.threshold}${check.unit || ''})`
          : (check.message || check.label);
        sections.push(`- :x: ${detail}`);
      }
      if (failedChecks.length > MAX_ISSUES) {
        sections.push(`- ... and ${failedChecks.length - MAX_ISSUES} more`);
      }

      sections.push('');
      sections.push(`</details>`);
      sections.push('');
    }
  }

  // Site-wide audit issues (redirects, links)
  for (const [auditName, result] of Object.entries(results.siteWide)) {
    if (result.failCount === 0) continue;

    const failedChecks = result.checks.filter(c => !c.passed);
    if (failedChecks.length === 0) continue;

    sections.push(`<details>`);
    sections.push(`<summary><b>${auditName}</b> — site-wide (${result.failCount} issue(s))</summary>`);
    sections.push('');

    for (const check of failedChecks.slice(0, MAX_ISSUES)) {
      sections.push(`- :x: ${check.message || check.label}`);
    }
    if (failedChecks.length > MAX_ISSUES) {
      sections.push(`- ... and ${failedChecks.length - MAX_ISSUES} more`);
    }

    sections.push('');
    sections.push(`</details>`);
    sections.push('');
  }

  return sections;
}

/**
 * Extract pathname from a URL, falling back to the full string.
 */
function safePathname(url) {
  try {
    return new URL(url).pathname;
  } catch {
    return url;
  }
}

/**
 * Truncate Markdown to a max length, appending a truncation notice.
 */
function truncate(text, maxLength) {
  if (text.length <= maxLength) return text;
  const notice = '\n\n---\n*Report truncated due to size. See full results in the workflow artifacts.*';
  return text.slice(0, maxLength - notice.length) + notice;
}
